# These are packages that are related to configuring parts of the system.
# It is intended to be kept generic so that it may be shared downstream with
# RHCOS.

packages:
  # Configuring SSH keys, cloud provider check-in, etc
  - afterburn afterburn-dracut
  # NTP support
  - chrony
  # Installing CoreOS itself
  - coreos-installer coreos-installer-bootinfra
  # Storage configuration/management
  ## cloud-utils-growpart - For growing root partition
  - cifs-utils
  - cloud-utils-growpart
  - cryptsetup
  - device-mapper-multipath
  - e2fsprogs
  - iscsi-initiator-utils
  - lvm2
  - mdadm
  - sg3_utils
  - xfsprogs
  # User configuration
  - passwd
  - shadow-utils
  - acl
  # SELinux policy
  - selinux-policy-targeted
  # There are things that write outside of the journal still (such as the
  # classic wtmp, etc.). auditd also writes outside the journal but it has its
  # own log rotation.
  # Anything package layered will also tend to expect files dropped in
  # /etc/logrotate.d to work. Really, this is a legacy thing, but if we don't
  # have it then people's disks will slowly fill up with logs.
  - logrotate
  # Boost starving threads
  # https://github.com/coreos/fedora-coreos-tracker/issues/753
  - stalld
  # Ignition aware SSH key management
  - ssh-key-dir

postprocess:
  # Mask systemd-repart. Ignition is responsible for partition setup on first
  # boot and does not use systemd-repart currently. See also
  # https://github.com/coreos/fedora-coreos-tracker/issues/570
  - |
    #!/usr/bin/env bash
    systemctl mask systemd-repart.service
