name: Update software versions

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-versions:
    name: Update versions
    if: ${{ github.repository_owner == 'coreos' || github.event_name != 'schedule' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ci/update-versions.py
      - name: Create commit
        run: |
          git config user.name 'CoreOS Bot'
          git config user.email coreosbot@fedoraproject.org
          if ! git diff --quiet --exit-code; then
              git commit -am "antora: update software versions ✨" \
                  -m "Triggered by update-versions GitHub Action."
          fi
      - name: Open pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.COREOSBOT_RELENG_TOKEN }}
          branch: update-versions
          push-to-fork: coreosbot-releng/fedora-coreos-docs
          title: "antora: update software versions ✨"
          body: "Created by update-versions [GitHub workflow](${{ github.server_url }}/${{ github.repository }}/actions/workflows/update-versions.yml) ([source](${{ github.server_url }}/${{ github.repository }}/blob/main/.github/workflows/update-versions.yml))."
          committer: "CoreOS Bot <coreosbot@fedoraproject.org>"
          author: "CoreOS Bot <coreosbot@fedoraproject.org>"
